### ISSUE TITLE
unable to access container through network namespace

### ISSUE THREAD

**Issue by nayabatir1** [saiyam1814/DevOpsRoadmap2022#305]
```yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
```

I used this yml config to create a pod.
I tried to access pod through network namespace, but unable to do so resulted in connection timeout.
but when curl inside the container index.html loads correctly.

![image](https://user-images.githubusercontent.com/91016903/159057413-409a6d31-dcac-4d09-abcb-8f86c505a25c.png)
![image](https://user-images.githubusercontent.com/91016903/159057459-d89b43ab-9f09-4b11-9102-fbb0c5535ed4.png)

@saiyam1814 need your help
